config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "tenkens#index"
  resources :users, only: [:edit, :update]
  resources :tenkens, except: :new do
      resources :checksheets, except: :index do
        resources :comments, only: [:create, :destroy]
      end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/checksheet.rb
class Checksheet < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :classroom
  belongs_to :tenken
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :image

  with_options presence: true do
    validates :classroom_id, numericality: { other_than: 0, message: "can't be blank" }
    validates :staff
    validates :date
    validates :status
  end
end

app/models/classroom.rb
class Classroom < ActiveHash::Base
  self.data = [
    { id: 0, number: '--' },
    { id: 1, number: '001' },
    { id: 2, number: '002' },
    { id: 3, number: '003' },
    { id: 4, number: '004' },
    { id: 5, number: '005' },
    { id: 6, number: '006' },
    { id: 7, number: '007' },
    { id: 8, number: '008' },
    { id: 9, number: '009' },
    { id: 10, number: '201' },
    { id: 11, number: '202' },
    { id: 12, number: '203' },
    { id: 13, number: '204' },
    { id: 14, number: '205' },
    { id: 15, number: '206' },
    { id: 16, number: '207' },
    { id: 17, number: '208' },
    { id: 18, number: '209' },
    { id: 19, number: '301' },
    { id: 20, number: '302' },
    { id: 21, number: '303' },
    { id: 22, number: '304' },
    { id: 23, number: '305' },
    { id: 24, number: '306' },
    { id: 25, number: '307' },
    { id: 26, number: '308' },
    { id: 27, number: '309' }
  ]

  include ActiveHash::Associations
  has_many :checksheets
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :checksheet
  has_one_attached :image

  validates :text, presence: true, unless: :was_attached?

  def was_attached?
    image.attached?
  end
end

app/models/tenken.rb
class Tenken < ApplicationRecord
  belongs_to :user
  has_many :checksheets, dependent: :destroy

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tenkens
  has_many :checksheets
  has_many :comments

  validates :nickname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/checksheets_controller.rb
class ChecksheetsController < ApplicationController
  before_action :set_tenken
  before_action :set_checksheet, only: [:show, :edit, :update, :destroy]

  def new
    @checksheet = @tenken.checksheets.new
  end

  def create
    @checksheet = @tenken.checksheets.new(checksheet_params)
    if @checksheet.save
      redirect_to tenken_path(@tenken.id)
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @checksheet.comments.includes(:user).order('created_at DESC')
  end

  def edit
  end

  def update
    if @checksheet.update(checksheet_params)
      redirect_to tenken_path(@tenken.id)
    else
      render :edit
    end
  end

  def destroy
    @checksheet.destroy
    redirect_to tenken_path(@tenken.id)
  end

  private

  def set_tenken
    @tenken = Tenken.find(params[:tenken_id])
  end

  def set_checksheet
    @checksheet = @tenken.checksheets.find(params[:id])
  end

  def checksheet_params
    params.require(:checksheet).permit(:classroom_id, :projector, :control_panel, :mic, :pc, :bd_dvd_player, :remotes, :ohc, :screen, :ports, :cables, :expendables, :details, :staff, :helper, :date, :status, :image).merge(
      tenken_id: params[:tenken_id], user_id: current_user.id
    )
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/tenkens/#{comment.checksheet.tenken.id}/checksheets/#{comment.checksheet.id}"
  end

  def destroy
    comment = Comment.find(params[:id])
    checksheet = comment.checksheet
    comment.destroy
    redirect_to "/tenkens/#{checksheet.tenken.id}/checksheets/#{checksheet.id}"
  end

  private

  def comment_params
    params.require(:comment).permit(:text, :image).merge(user_id: current_user.id, checksheet_id: params[:checksheet_id])
  end
end

app/controllers/tenkens_controller.rb
class TenkensController < ApplicationController
  before_action :set_tenken, only: [:show, :edit, :update, :destroy]
  def index
    @tenken = Tenken.new
    @tenkens = Tenken.includes(:user).order('created_at DESC')
  end

  def create
    Tenken.create(tenken_params)
    redirect_to root_path
  end

  def show
    @checksheets = @tenken.checksheets.order('classroom_id ASC')
    @classrooms = pending_classrooms(@checksheets)
  end

  def edit
  end

  def update
    if @tenken.update(tenken_params)
      redirect_to tenken_path(@tenken.id)
    else
      redirect_to action: :edit
    end
  end

  def destroy
    @tenken.destroy
    redirect_to root_path
  end

  private

  def tenken_params
    params.require(:tenken).permit(:name).merge(user_id: current_user.id)
  end

  def set_tenken
    @tenken = Tenken.find(params[:id])
  end

  def pending_classrooms(checksheets)
    done = []
    pending = []
    checksheets.each do |checksheet|
      done << checksheet[:classroom_id]
    end
    classrooms = Classroom.all
    classrooms.each do |classroom|
      pending << classroom unless done.include?(classroom[:id]) || classroom[:id] == 0
    end
    pending
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checksheets_helper.rb
module ChecksheetsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tenkens_helper.rb
module TenkensHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/checksheets/_form.html.erb
<div class="container d-flex flex-column my-5">

<div class='row d-flex mb-md-3 mb-2'>
<p class='col-md-4'>
<%= link_to "教室一覧へ戻る", tenken_path(@tenken.id), class:"link-primary fs-5" %></p>
<div class='col-md-4'> </div>
</div>

<%= form_with model:([@tenken,@checksheet]), local: true do |f| %>
 <div class='row d-flex'>
 <p class='col-md-4 mb-md-2 mb-0 mt-md-0 mt-2'>教室番号【必須】</p>
 <div class='col-md-4'>
  <%= f.collection_select(:classroom_id, Classroom.all, :id, :number, {}, {class:"form-select"}) %>
  </div>
  </div>
  
  <div class='row d-flex'>
  <p class='col-md-4 mb-md-2 mb-0 mt-md-0 mt-2'>プロジェクター</p>
  <div class='col-md-4'>
  <%= f.select :projector, {"OK":"OK", "NG":"NG"}, {include_blank: "--"}, {class:'form-select'} %>
  </div>
  </div>

  <div class='row d-flex'>
   <p class='col-md-4 mb-md-2 mb-0 mt-md-0 mt-2'>コンパネ</p>
  <div class='col-md-4'>
   <%= f.select :control_panel, {"OK":"OK", "NG":"NG"}, {include_blank: "--"}, {class:'form-select'} %>
  </div>
  </div>

  <div class='row d-flex'>
  <p class='col-md-4 mb-md-2 mb-0 mt-md-0 mt-2'>マイク</p>
  <div class='col-md-4'>
  <%= f.select :mic, {"OK":"OK", "NG":"NG"}, {include_blank: "--"}, {class:'form-select'} %>
  </div>
  </div>

  <div class='row d-flex'>
  <p class='col-md-4 mb-md-2 mb-0 mt-md-0 mt-2'>パソコン</p>
  <div class='col-md-4'>
  <%= f.select :pc, {"OK":"OK", "NG":"NG"}, {include_blank: "--"}, {class:'form-select'} %>
  </div>
  </div>

  <div class='row d-flex'>
  <p class='col-md-4 mb-md-2 mb-0 mt-md-0 mt-2'>Blu-ray/DVDデッキ</p>
  <div class='col-md-4'>
  <%= f.select :bd_dvd_player, {"OK":"OK", "NG":"NG"}, {include_blank: "--"}, {class:'form-select'} %>
  </div>
  </div>

  <div class='row d-flex'>
  <p class='col-md-4 mb-md-2 mb-0 mt-md-0 mt-2'>リモコン</p>
  <div class='col-md-4'>
  <%= f.select :remotes, {"OK":"OK", "NG":"NG", "電池交換済":"電池交換済"}, {include_blank: "--"}, {class:'form-select'} %>
  </div>
   </div>

  <div class='row d-flex'>
  <p class='col-md-4 mb-md-2 mb-0 mt-md-0 mt-2'>書画カメラ</p>
  <div class='col-md-4'>
   <%= f.select :ohc, {"OK":"OK", "NG":"NG"}, {include_blank: "--"}, {class:'form-select'} %>
  </div>
  </div>

  <div class='row d-flex'>
  <p class='col-md-4 mb-md-2 mb-0 mt-md-0 mt-2'>スクリーン</p>
 <div class='col-md-4'>
  <%= f.select :screen, {"OK":"OK", "NG":"NG"}, {include_blank: "--"}, {class:'form-select'} %>
  </div>
  </div>

  <div class='row d-flex'>
  <p class='col-md-4 mb-md-2 mb-0 mt-md-0 mt-2'>持込用端子</p>
  <div class='col-md-4'>
   <%= f.select :ports, {"OK":"OK", "NG":"NG"}, {include_blank: "--"}, {class:'form-select'} %>
  </div>
  </div>

  <div class='row d-flex'>
  <p class='col-md-4 mb-md-2 mb-0 mt-md-0 mt-2'>持込用ケーブル</p>
  <div class='col-md-4'>
 <%= f.select :cables, {"OK":"OK", "NG":"NG"}, {include_blank: "--"}, {class:'form-select'} %>
  </div>
  </div>

  <div class='row d-flex'>
  <p class='col-md-4 mb-md-2 mb-0 mt-md-0 mt-2'>消耗品</p>
 <div class='col-md-4'>
  <%= f.select :expendables, {"OK":"OK", "補充済":"補充済", "交換済":"交換済"}, {include_blank: "--"}, {class:'form-select'} %>
  </div>
  </div>

  <div class='row d-flex'>
  <p class='col-md-4 mb-md-2 mb-0 mt-md-0 mt-2'>詳細、コメント等</p>
  <div class='col-md-4'>
  <%= f.text_area :details, class:"form-control", rows: "3"%>
  <%= f.file_field :image %>
  </div>
   </div>

  <div class='row d-flex'>
  <p class='col-md-4 mb-md-2 mb-0 mt-md-0 mt-2'>担当者１【必須】</p>
 <div class='col-md-4'>
  <%= f.collection_select(:staff, User.all, :nickname, :nickname, {include_blank: "--"}, {class:'form-select'}) %>
  </div>
   </div>

  <div class='row d-flex'>
  <p class='col-md-4 mb-md-2 mb-0 mt-md-0 mt-2'>担当者２</p>
  <div class='col-md-4'>
  <%= f.collection_select(:helper, User.all, :nickname, :nickname, {include_blank: "--"}, {class:'form-select'}) %>
  </div>
  </div>

  <div class='row d-flex'>
   <p class='col-md-4 mb-md-2 mb-0 mt-md-0 mt-2'>実施日【必須】</p>
   <div class='col-md-4 d-flex'>
  <%= raw sprintf(
    f.date_select(
      :date,
      class:'date-select',
      use_month_numbers: true,
      prompt: '--',
      start_year: 2015,
      end_year: (Time.now.year),
      date_separator: '%s'),
      "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>"%>
  </div>
  </div>

  <div class='row d-flex'>
   <p class='col-md-4 mb-md-2 mb-0 mt-md-0 mt-2'>進捗状況【必須】</p>
  <div class='col-md-4'>
   <%= f.select :status, {"対応中":"対応中", "完了":"完了"}, {include_blank: "--"}, {class:'form-select'} %>
  </div>
   </div>

<div class="container d-flex ps-0">
<%= f.submit "送信", class:"btn btn-primary mt-3 px-5" %>
</div>
  <% end %>
 

</div>

app/views/checksheets/edit.html.erb
<%= render "form" %>

app/views/checksheets/new.html.erb
<%= render "form" %>

app/views/checksheets/show.html.erb
<div class='container d-flex flex-column my-5'>

  <div class='row d-flex mb-md-3 mb-2'>
    <p class='col-md-4'><%= link_to "教室一覧へ戻る", tenken_path(@tenken.id), class:"link-primary fs-5" %></p>
    <div class='col-md-4'> </div>
  </div>

  <table class="table mb-md-5 mb-3">
  <thead>
    <tr>
      <th scope="col">教室番号</th>
      <th scope="col">
      <%= @checksheet.classroom.number %>
      <%= link_to edit_tenken_checksheet_path(@tenken.id, @checksheet.id) do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-pencil ms-3" viewBox="0 0 16 16">
        <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
        </svg>
      <% end %>
      <%= link_to tenken_checksheet_path(@tenken.id, @checksheet.id), method: :delete do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-trash ms-3" viewBox="0 0 16 16">
      <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
      <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
      </svg>
     <% end %>
      </th>
    </tr>
  </thead>
  <tbody>
     <tr>
      <td>プロジェクター</td>
      <td><%= @checksheet.projector %></td>
    </tr>
    <tr>
      <td>コントロールパネル</td>
      <td><%= @checksheet.control_panel %></td>
    </tr>
    <tr>
      <td>マイク</td>
      <td><%= @checksheet.mic %></td>
    </tr>
    <tr>
      <td>パソコン</td>
      <td><%= @checksheet.pc %></td>
    </tr>
    <tr>
      <td>Blu-ray/DVDデッキ</td>
      <td><%= @checksheet.bd_dvd_player %></td>
    </tr>
    <tr>
      <td>リモコン</td>
      <td><%= @checksheet.remotes %></td>
    </tr>
    <tr>
      <td>書画カメラ</td>
      <td><%= @checksheet.ohc %></td>
    </tr>
    <tr>
      <td>スクリーン</td>
      <td><%= @checksheet.screen %></td>
    </tr>
    <tr>
      <td>持込用端子</td>
      <td><%= @checksheet.ports %></td>
    </tr>
    <tr>
      <td>持込用ケーブル</td>
      <td><%= @checksheet.cables %></td>
    </tr>
    <tr>
      <td>消耗品</td>
      <td><%= @checksheet.expendables %></td>
    </tr>
    <tr>
      <td>詳細</td>
      <td>
      <div>
      <%= @checksheet.details %>
      </div>
      <%= image_tag @checksheet.image.variant(resize: '500x500'), class:'img-fluid' if @checksheet.image.attached? %>
      </td>
    </tr>
     <tr>
      <td>担当者１</td>
      <td><%= @checksheet.staff %></td>
    </tr>
     <tr>
      <td>担当者２</td>
      <td><%= @checksheet.helper %></td>
    </tr>
    <tr>
      <td>実施日</td>
      <td><%= @checksheet.date %></td>
    </tr>
    <tr>
      <td>進捗状況</td>
      <td><%= @checksheet.status %></td>
    </tr>

    </tbody>
  </table>


  <div class="container">
    <div>
        <%= form_with model:([@tenken, @checksheet, @comment]), local: true do |f| %>
        <%= f.text_area :text, class:"form-control", placeholder: "コメントする", rows: "3" %>
        <%= f.file_field :image %>
        <%= f.submit "送信", class:"btn btn-secondary mt-3 px-5" %>
       <% end %>
    </div>

<hr/>

  <div class="mt-md-5 mt-3">
    <h3 class="p-3 text-center">コメント一覧</h3>
    <%= render partial: 'comments/comment' , collection: @comments %>
  </div>
</div>

app/views/comments/_comment.html.erb
<div class="container bg-white mt-3 p-3">
  <div>     
    <span class="text-secondary">
    <%= comment.created_at.to_s(:datetime) %>
    by <%= comment.user.nickname %>
    <% if comment.user_id == current_user.id %>
      <%= link_to tenken_checksheet_comment_path(comment.checksheet.tenken_id, comment.checksheet_id, comment.id), method: :delete do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-trash ms-3" viewBox="0 0 16 16">
      <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
      <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
      </svg>
     <% end %>
     <% end %>
    </span>
  </div>
  <div>
  <%= comment.text %>
  <%= image_tag comment.image.variant(resize: '500x500'), class:'img-fluid mt-2' if comment.image.attached? %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TenkenApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column align-items-stretch bg-light">
    <%= yield %>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class='bg-dark p-4 text-center'>
<%= link_to '2021 TenkenApp (c)', '/', class:'text-light fs-5' %>
</footer>

app/views/shared/_header.html.erb
<header>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark p-3">
  <div class="container-fluid">
  <%= link_to 'TenkenApp', '/', class:'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
       <li class="nav-item"><%= link_to current_user.nickname, edit_user_path(current_user), class:'nav-link' %></li>
        <li class="nav-item"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:'nav-link'%></li>
      </ul>
    </div>
  </div>
</nav>
</header>

app/views/tenkens/show.html.erb
<%= render "shared/header" %>
<div class='main'>

  <div class='container d-md-flex justify-content-center my-5 tenken-title-button'>
    <div class='d-flex'>
      <h3 class='m-0 lh-lg'><%= @tenken.name %></h3>
      <%= link_to edit_tenken_path(@tenken.id) do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-pencil ms-3" viewBox="0 0 16 16">
        <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
        </svg>
      <% end %>
     <%= link_to tenken_path(@tenken.id), method: :delete do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-trash ms-3" viewBox="0 0 16 16">
      <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
      <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
      </svg>
     <% end %>
    </div>
    <%= link_to new_tenken_checksheet_path(@tenken.id) do %> 
    <button class='text-light btn bg-primary btn-lg ms-md-5 mt-md-0 mt-sm-3'>点検を開始</button>
    <% end %>
  </div>

<hr>
  <div class='container mt-5 mb-md-5 button-container'>
    <h3 class="text-center mb-md-5">対応中・対応完了の教室</h3>
    <div class='container d-flex flex-wrap justify-content-center'>
    <% @checksheets.each do |checksheet| %>
    <%= link_to tenken_checksheet_path(checksheet.tenken_id, checksheet.id), class:'btn bg-success me-2 mb-2 text-light', style: 'width: 77px;' do %>
    <%= checksheet.classroom.number %>
        <% if checksheet.status == "完了" %>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-circle text-light" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
        <path d="M10.97 4.97a.235.235 0 0 0-.02.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05z"/>
        </svg>
        <% end %>
        <% if checksheet.status == "対応中" %>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-exclamation-triangle text-light" viewBox="0 0 16 16">
        <path d="M7.938 2.016A.13.13 0 0 1 8.002 2a.13.13 0 0 1 .063.016.146.146 0 0 1 .054.057l6.857 11.667c.036.06.035.124.002.183a.163.163 0 0 1-.054.06.116.116 0 0 1-.066.017H1.146a.115.115 0 0 1-.066-.017.163.163 0 0 1-.054-.06.176.176 0 0 1 .002-.183L7.884 2.073a.147.147 0 0 1 .054-.057zm1.044-.45a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566z"/>
       <path d="M7.002 12a1 1 0 1 1 2 0 1 1 0 0 1-2 0zM7.1 5.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995z"/>
      </svg>
        <% end %>
    <% end %>
    <% end %>
    </div>
  </div>

  <div class='container d-flex mb-5 p-3 shadow-sm'>
   <p class="fs-6 mb-0">未着手の教室：
      <% @classrooms.each do |classroom| %>
      <%= classroom.number %>
      <% end %>
   </p>
  </div>

</div>
<%= render "shared/footer" %>